title: petrosh
baseurl: /daisu
description: Raw minimal theme for Jekyll
permalink: pretty

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      menu: 0
      comments: false

# Assets
js:
  - beyond-blog
css:
  - style

# Custom css
colors:
  - link_color: "#4078c0"
  - grey_color: "#7f7f7f"

# show breadcrumb
show_breadcrumb: true
